version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "circuit-breaker-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-172pf1qfjyeuu"
s3_prefix = "circuit-breaker-stack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "default"
